# Generated by Django 5.2.4 on 2025-08-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_product_image_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
